INSERT INTO UserDB (name, email) VALUES ('John', 'john@domain.com')
INSERT INTO UserDB (name, email) VALUES ('Jose', 'jose@domain.com')
INSERT INTO UserDB (name, email) VALUES ('Rachel', 'rache@domain.com')
INSERT INTO UserDB (name, email) VALUES ('Reese', 'reese@domain.com')
INSERT INTO UserDB (name, email) VALUES ('Reese', 'reese123@domain.com')
INSERT INTO UserDB (name, email) VALUES ('Manu', 'manu@domain.com')
INSERT INTO Event (title, date) VALUES ('The King Lion', '2022-04-04')
INSERT INTO Event (title, date) VALUES ('The King Lion', '2022-04-05')
INSERT INTO Event (title, date) VALUES ('Hamlet', '2020-02-03')
INSERT INTO Event (title, date) VALUES ('Hamlet', '2015-08-08')
INSERT INTO Event (title, date) VALUES ('Who is afraid of Virginia Wolf?', '2021-04-04')
INSERT INTO Event (title, date) VALUES ('Who is afraid of Virginia Wolf?', '2021-04-07')
INSERT INTO Event (title, date) VALUES ('Death of a Salesman', '2015-08-08')
INSERT INTO Event (title, date) VALUES ('Death of a Salesman', '2013-08-10')
INSERT INTO Event (title, date) VALUES ('Angels of America', '2015-08-08')
INSERT INTO Event (title, date) VALUES ('Angels of America', '2015-09-10')
INSERT INTO Event (title, date) VALUES ('Angles of America', '2015-09-11')
INSERT INTO Event (title, date) VALUES ('Angles of America', '2015-09-13')
INSERT INTO Ticket (category, place, event_id, user_id) VALUES ('BAR', 34, 1, 1)
INSERT INTO Ticket (category, place, event_id, user_id) VALUES ('BAR', 34, 1, 2)
INSERT INTO Ticket (category, place, event_id, user_id) VALUES ('STANDARD', 24, 3, 3)
INSERT INTO Ticket (category, place, event_id, user_id) VALUES ('STANDARD', 24, 3, 1)
INSERT INTO Ticket (category, place, event_id, user_id) VALUES ('PREMIUM', 55, 4, 4)